{% set name = "geomesher" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geomesher-{{ version }}.tar.gz
  sha256: 049218ad13f42f7d223a8526acd0b516f98fb6ad8b24df31d1e7f960a9a00e4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - pandas
    - geopandas-base
    - gmsh
    - python-gmsh
    - scipy
    - shapely >=2.0

test:
  imports:
    - geomesher
    # skip it for now b/c both geopandas and gmsh require package metadata correction
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/geomesher
  summary: Meshing a GeoDataFrame using Gmsh.
  description: |
    GeoMesher uses Gmsh to generate unstructured mesh from
    an input GeoDataFrame and can additionally remap a scalar
    field from the source geodataframe to the generated mesh.
  license: MIT
  license_file: LICENSE
  doc_url: https://geomesher.readthedocs.io/

extra:
  recipe-maintainers:
    - cheginit
